export type StoreCardDetailsProps = {
  holderName: string;
  holderId: string;
  kind: string;
  date: string;
  address: string;
  customTitle: string;
  customValue: string;
  startDate: string;
  endDate: string;
  description: string;
  phoneNumber: string;
  phoneNumberSecondary: string;
  website: string;
  disableNotifications?: string;
  holderNameTitle?: string;
  holderIdTitle?: string;
  kindTitle?: string;
  addressTitle?: string;
  scheduleTitle?: string;
  offersTitle?: string;
  phoneNumberTitle?: string;
  phoneNumberSecondaryTitle?: string;
};
